fragment AboutParts on About {
  __typename
  title_es
  title_en
  purpose_es
  purpose_en
  mission_es
  mission_en
  vision_es
  vision_en
  values {
    __typename
    title_es
    title_en
    description_es
    description_en
  }
}

fragment ExploreParts on Explore {
  __typename
  attractions {
    __typename
    id
    name_es
    name_en
    description_es
    description_en
    distance
    travelTime
    category
    history_es
    history_en
    howToGet_es
    howToGet_en
    tips_es
    tips_en
    bestTime_es
    bestTime_en
    image
  }
}

fragment FaqParts on Faq {
  __typename
  questions {
    __typename
    question_es
    question_en
    answer_es
    answer_en
  }
}

fragment RoomsParts on Rooms {
  __typename
  rooms {
    __typename
    id
    slug
    name_es
    name_en
    description_es
    description_en
    maxGuests
    beds
    pricePerNight
    amenities
    images
    photoFolder
    hasVideoTour
    amenityLabels {
      __typename
      wifi {
        __typename
        es
        en
      }
      breakfast {
        __typename
        es
        en
      }
      hot_water {
        __typename
        es
        en
      }
      heating {
        __typename
        es
        en
      }
      tv {
        __typename
        es
        en
      }
      laundry {
        __typename
        es
        en
      }
    }
  }
}

fragment ServicesParts on Services {
  __typename
  services {
    __typename
    id
    name_es
    name_en
    description_es
    description_en
    icon
  }
}

fragment ReviewsParts on Reviews {
  __typename
  reviews {
    __typename
    name
    country
    rating
    text_es
    text_en
    date_es
    date_en
  }
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  hotelName
  phone
  phoneRaw
  email
  whatsappNumber
  streetAddress
  city
  region
  postalCode
  country
  address_es
  address_en
  latitude
  longitude
  checkinTime
  checkoutTime
  starRating
  priceRange
  siteDescription_es
  siteDescription_en
  socialLinks {
    __typename
    platform
    url
    label
  }
}
