//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  about: About;
  aboutConnection: AboutConnection;
  explore: Explore;
  exploreConnection: ExploreConnection;
  faq: Faq;
  faqConnection: FaqConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryExploreArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExploreConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExploreFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};

export type DocumentFilter = {
  about?: InputMaybe<AboutFilter>;
  explore?: InputMaybe<ExploreFilter>;
  faq?: InputMaybe<FaqFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = About | Explore | Faq | Folder;

export type AboutValues = {
  __typename?: 'AboutValues';
  title_es?: Maybe<Scalars['String']['output']>;
  title_en?: Maybe<Scalars['String']['output']>;
  description_es?: Maybe<Scalars['String']['output']>;
  description_en?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  title_es: Scalars['String']['output'];
  title_en: Scalars['String']['output'];
  purpose_es: Scalars['String']['output'];
  purpose_en: Scalars['String']['output'];
  mission_es: Scalars['String']['output'];
  mission_en: Scalars['String']['output'];
  vision_es: Scalars['String']['output'];
  vision_en: Scalars['String']['output'];
  values?: Maybe<Array<Maybe<AboutValues>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AboutValuesFilter = {
  title_es?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  description_es?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  title_es?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  purpose_es?: InputMaybe<StringFilter>;
  purpose_en?: InputMaybe<StringFilter>;
  mission_es?: InputMaybe<StringFilter>;
  mission_en?: InputMaybe<StringFilter>;
  vision_es?: InputMaybe<StringFilter>;
  vision_en?: InputMaybe<StringFilter>;
  values?: InputMaybe<AboutValuesFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ExploreAttractions = {
  __typename?: 'ExploreAttractions';
  id: Scalars['String']['output'];
  name_es: Scalars['String']['output'];
  name_en: Scalars['String']['output'];
  description_es: Scalars['String']['output'];
  description_en: Scalars['String']['output'];
  distance: Scalars['String']['output'];
  travelTime: Scalars['String']['output'];
  category: Scalars['String']['output'];
  history_es?: Maybe<Scalars['String']['output']>;
  history_en?: Maybe<Scalars['String']['output']>;
  howToGet_es?: Maybe<Scalars['String']['output']>;
  howToGet_en?: Maybe<Scalars['String']['output']>;
  tips_es?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tips_en?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bestTime_es?: Maybe<Scalars['String']['output']>;
  bestTime_en?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Explore = Node & Document & {
  __typename?: 'Explore';
  attractions?: Maybe<Array<Maybe<ExploreAttractions>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ExploreAttractionsFilter = {
  id?: InputMaybe<StringFilter>;
  name_es?: InputMaybe<StringFilter>;
  name_en?: InputMaybe<StringFilter>;
  description_es?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  distance?: InputMaybe<StringFilter>;
  travelTime?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  history_es?: InputMaybe<StringFilter>;
  history_en?: InputMaybe<StringFilter>;
  howToGet_es?: InputMaybe<StringFilter>;
  howToGet_en?: InputMaybe<StringFilter>;
  tips_es?: InputMaybe<StringFilter>;
  tips_en?: InputMaybe<StringFilter>;
  bestTime_es?: InputMaybe<StringFilter>;
  bestTime_en?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ExploreFilter = {
  attractions?: InputMaybe<ExploreAttractionsFilter>;
};

export type ExploreConnectionEdges = {
  __typename?: 'ExploreConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Explore>;
};

export type ExploreConnection = Connection & {
  __typename?: 'ExploreConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExploreConnectionEdges>>>;
};

export type FaqQuestions = {
  __typename?: 'FaqQuestions';
  question_es: Scalars['String']['output'];
  question_en: Scalars['String']['output'];
  answer_es: Scalars['String']['output'];
  answer_en: Scalars['String']['output'];
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  questions?: Maybe<Array<Maybe<FaqQuestions>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqQuestionsFilter = {
  question_es?: InputMaybe<StringFilter>;
  question_en?: InputMaybe<StringFilter>;
  answer_es?: InputMaybe<StringFilter>;
  answer_en?: InputMaybe<StringFilter>;
};

export type FaqFilter = {
  questions?: InputMaybe<FaqQuestionsFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAbout: About;
  createAbout: About;
  updateExplore: Explore;
  createExplore: Explore;
  updateFaq: Faq;
  createFaq: Faq;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateExploreArgs = {
  relativePath: Scalars['String']['input'];
  params: ExploreMutation;
};


export type MutationCreateExploreArgs = {
  relativePath: Scalars['String']['input'];
  params: ExploreMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};

export type DocumentUpdateMutation = {
  about?: InputMaybe<AboutMutation>;
  explore?: InputMaybe<ExploreMutation>;
  faq?: InputMaybe<FaqMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  about?: InputMaybe<AboutMutation>;
  explore?: InputMaybe<ExploreMutation>;
  faq?: InputMaybe<FaqMutation>;
};

export type AboutValuesMutation = {
  title_es?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  description_es?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  title_es?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  purpose_es?: InputMaybe<Scalars['String']['input']>;
  purpose_en?: InputMaybe<Scalars['String']['input']>;
  mission_es?: InputMaybe<Scalars['String']['input']>;
  mission_en?: InputMaybe<Scalars['String']['input']>;
  vision_es?: InputMaybe<Scalars['String']['input']>;
  vision_en?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<AboutValuesMutation>>>;
};

export type ExploreAttractionsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name_es?: InputMaybe<Scalars['String']['input']>;
  name_en?: InputMaybe<Scalars['String']['input']>;
  description_es?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  distance?: InputMaybe<Scalars['String']['input']>;
  travelTime?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  history_es?: InputMaybe<Scalars['String']['input']>;
  history_en?: InputMaybe<Scalars['String']['input']>;
  howToGet_es?: InputMaybe<Scalars['String']['input']>;
  howToGet_en?: InputMaybe<Scalars['String']['input']>;
  tips_es?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tips_en?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bestTime_es?: InputMaybe<Scalars['String']['input']>;
  bestTime_en?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ExploreMutation = {
  attractions?: InputMaybe<Array<InputMaybe<ExploreAttractionsMutation>>>;
};

export type FaqQuestionsMutation = {
  question_es?: InputMaybe<Scalars['String']['input']>;
  question_en?: InputMaybe<Scalars['String']['input']>;
  answer_es?: InputMaybe<Scalars['String']['input']>;
  answer_en?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  questions?: InputMaybe<Array<InputMaybe<FaqQuestionsMutation>>>;
};

export type AboutPartsFragment = { __typename: 'About', title_es: string, title_en: string, purpose_es: string, purpose_en: string, mission_es: string, mission_en: string, vision_es: string, vision_en: string, values?: Array<{ __typename: 'AboutValues', title_es?: string | null, title_en?: string | null, description_es?: string | null, description_en?: string | null } | null> | null };

export type ExplorePartsFragment = { __typename: 'Explore', attractions?: Array<{ __typename: 'ExploreAttractions', id: string, name_es: string, name_en: string, description_es: string, description_en: string, distance: string, travelTime: string, category: string, history_es?: string | null, history_en?: string | null, howToGet_es?: string | null, howToGet_en?: string | null, tips_es?: Array<string | null> | null, tips_en?: Array<string | null> | null, bestTime_es?: string | null, bestTime_en?: string | null, image?: string | null } | null> | null };

export type FaqPartsFragment = { __typename: 'Faq', questions?: Array<{ __typename: 'FaqQuestions', question_es: string, question_en: string, answer_es: string, answer_en: string } | null> | null };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, title_es: string, title_en: string, purpose_es: string, purpose_en: string, mission_es: string, mission_en: string, vision_es: string, vision_en: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutValues', title_es?: string | null, title_en?: string | null, description_es?: string | null, description_en?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, title_es: string, title_en: string, purpose_es: string, purpose_en: string, mission_es: string, mission_en: string, vision_es: string, vision_en: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutValues', title_es?: string | null, title_en?: string | null, description_es?: string | null, description_en?: string | null } | null> | null } | null } | null> | null } };

export type ExploreQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExploreQuery = { __typename?: 'Query', explore: { __typename: 'Explore', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, attractions?: Array<{ __typename: 'ExploreAttractions', id: string, name_es: string, name_en: string, description_es: string, description_en: string, distance: string, travelTime: string, category: string, history_es?: string | null, history_en?: string | null, howToGet_es?: string | null, howToGet_en?: string | null, tips_es?: Array<string | null> | null, tips_en?: Array<string | null> | null, bestTime_es?: string | null, bestTime_en?: string | null, image?: string | null } | null> | null } };

export type ExploreConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExploreFilter>;
}>;


export type ExploreConnectionQuery = { __typename?: 'Query', exploreConnection: { __typename?: 'ExploreConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExploreConnectionEdges', cursor: string, node?: { __typename: 'Explore', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, attractions?: Array<{ __typename: 'ExploreAttractions', id: string, name_es: string, name_en: string, description_es: string, description_en: string, distance: string, travelTime: string, category: string, history_es?: string | null, history_en?: string | null, howToGet_es?: string | null, howToGet_en?: string | null, tips_es?: Array<string | null> | null, tips_en?: Array<string | null> | null, bestTime_es?: string | null, bestTime_en?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, questions?: Array<{ __typename: 'FaqQuestions', question_es: string, question_en: string, answer_es: string, answer_en: string } | null> | null } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, questions?: Array<{ __typename: 'FaqQuestions', question_es: string, question_en: string, answer_es: string, answer_en: string } | null> | null } | null } | null> | null } };

export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  title_es
  title_en
  purpose_es
  purpose_en
  mission_es
  mission_en
  vision_es
  vision_en
  values {
    __typename
    title_es
    title_en
    description_es
    description_en
  }
}
    `;
export const ExplorePartsFragmentDoc = gql`
    fragment ExploreParts on Explore {
  __typename
  attractions {
    __typename
    id
    name_es
    name_en
    description_es
    description_en
    distance
    travelTime
    category
    history_es
    history_en
    howToGet_es
    howToGet_en
    tips_es
    tips_en
    bestTime_es
    bestTime_en
    image
  }
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  questions {
    __typename
    question_es
    question_en
    answer_es
    answer_en
  }
}
    `;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ExploreDocument = gql`
    query explore($relativePath: String!) {
  explore(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExploreParts
  }
}
    ${ExplorePartsFragmentDoc}`;
export const ExploreConnectionDocument = gql`
    query exploreConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExploreFilter) {
  exploreConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExploreParts
      }
    }
  }
}
    ${ExplorePartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    explore(variables: ExploreQueryVariables, options?: C): Promise<{data: ExploreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExploreQueryVariables, query: string}> {
        return requester<{data: ExploreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExploreQueryVariables, query: string}, ExploreQueryVariables>(ExploreDocument, variables, options);
      },
    exploreConnection(variables?: ExploreConnectionQueryVariables, options?: C): Promise<{data: ExploreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExploreConnectionQueryVariables, query: string}> {
        return requester<{data: ExploreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExploreConnectionQueryVariables, query: string}, ExploreConnectionQueryVariables>(ExploreConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/8d8990a6-978a-48a8-b88c-4b4e13bf2978/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  